// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEj6sEjwX9PGpwRJT4BIXbeuaog7T-dbs',
    appId: '1:816753520921:android:7d6da691fd88f6fe585588',
    messagingSenderId: '816753520921',
    projectId: 'spotify-app-8f19a',
    storageBucket: 'spotify-app-8f19a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTD-q86e8JjPnzFfh3Bab0AtNLSzb5vI',
    appId: '1:816753520921:ios:78b906991f316d31585588',
    messagingSenderId: '816753520921',
    projectId: 'spotify-app-8f19a',
    storageBucket: 'spotify-app-8f19a.firebasestorage.app',
    androidClientId: '816753520921-6ldhsb25nco86dkkvl0jdi44cu51g4ho.apps.googleusercontent.com',
    iosClientId: '816753520921-iukse5bf0maer1jv5cqt94btm9m0dkk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );
}
